# 투자 성향 클러스터링
- invest_session_id 
- child_id 
- sex 
- age 
- chapter_id
- trade_participation_turn (거래 참여 턴 개수)
- num_of_transaction (거래 횟수, +/- 클릭 횟수)
- avg_cash_ratio (평균 현금잔여율)
- turn_dwell_time (평균 턴 체류시간)
- buy_sell_ratio (고/중/저 구매/판매 비율)
- tag_turn_dwell_time (평균 tag 뉴스 발생 턴 체류시간)
- risk_tolerance (위험 감수율)
- bet_success_rate (배팅 성공율)

Child (PostgreSQL)
- child_id
- sex
- age

InvestHistory (MongoDB)
- invest_session_id
- chapter_id
- child_id
- turn
- risk_level
- current_point
- before_value
- current_value
- initial_value
- number_of_shares
- income
- transaction_type
tag추가

# MongoDB에서 바로 DataFrame으로 가져오기

In [149]:
from pymongo import MongoClient
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv(override=True)

# MongoDB 연결 정보
uri = os.getenv("MONGO_URI")
db_name = os.getenv("MONGO_DB_NAME")
collection_name = os.getenv("COLLECTION_NAME")

client = MongoClient(uri)
db = client[db_name]
collection = db[collection_name]

# MongoDB에서 데이터 불러오기
data = list(collection.find())

# DataFrame으로 변환
df = pd.DataFrame(data)
df.head()

,_id,investSessionId,chapterId,childId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class
0,b'oI\xae\x87\xbdcU\xc1\xe5}\xa5\x8d5\xba\\\xb2',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,고위험 고수익,900,0,100,100,5,0,BUY,5,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
1,b'4J\x1f\xc6\xaf\xfdw[F\xf1\x97\x80\x8dS\x8e\x99',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,균형형,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
2,b'\x81J\xf4\xad\xc3_\x01\x95!\x95\x07\x1b(\xf9...,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,장기 안정형,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
3,b'\xbbO\x1b\xb4j<\x81\x9f>\x08\x1b\x07z\xeb@\xb5',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,균형형,1670,100,110,100,1,20,SELL,0,2,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory
4,b':BtFH\xba\r%w.\xcfo1A\x0f\x92',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,고위험 고수익,1670,100,90,100,1,-40,SELL,0,4,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory

In [150]:
# 현재는 mongoDB에 childId라고 저장이 되어있는데 나중에 userId로 바뀔 예정이기 때문에 바꾸는 과정 추가해둠
### 나중에 삭제 될 코드
df.rename(columns={'childId':'userId'}, inplace=True)
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class
0,b'oI\xae\x87\xbdcU\xc1\xe5}\xa5\x8d5\xba\\\xb2',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,고위험 고수익,900,0,100,100,5,0,BUY,5,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
1,b'4J\x1f\xc6\xaf\xfdw[F\xf1\x97\x80\x8dS\x8e\x99',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,균형형,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
2,b'\x81J\xf4\xad\xc3_\x01\x95!\x95\x07\x1b(\xf9...,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,장기 안정형,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
3,b'\xbbO\x1b\xb4j<\x81\x9f>\x08\x1b\x07z\xeb@\xb5',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,균형형,1670,100,110,100,1,20,SELL,0,2,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory
4,b':BtFH\xba\r%w.\xcfo1A\x0f\x92',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,고위험 고수익,1670,100,90,100,1,-40,SELL,0,4,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory

In [151]:
# riskLevel 한영변환
df['riskLevel'] = df['riskLevel'].replace({
    '고위험 고수익': 'high',
    '균형형': 'mid',
    '장기 안정형': 'low'
})
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class
0,b'oI\xae\x87\xbdcU\xc1\xe5}\xa5\x8d5\xba\\\xb2',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,900,0,100,100,5,0,BUY,5,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
1,b'4J\x1f\xc6\xaf\xfdw[F\xf1\x97\x80\x8dS\x8e\x99',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,mid,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
2,b'\x81J\xf4\xad\xc3_\x01\x95!\x95\x07\x1b(\xf9...,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,low,900,0,100,100,3,0,BUY,3,0,2025-06-10 13:55:14,2025-06-10 13:55:18,com.popoworld.backend.invest.entity.InvestHistory
3,b'\xbbO\x1b\xb4j<\x81\x9f>\x08\x1b\x07z\xeb@\xb5',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,mid,1670,100,110,100,1,20,SELL,0,2,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory
4,b':BtFH\xba\r%w.\xcfo1A\x0f\x92',b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,1670,100,90,100,1,-40,SELL,0,4,2025-06-10 13:55:18,2025-06-10 13:55:22,com.popoworld.backend.invest.entity.InvestHistory

In [152]:
# 파생 변수 : 이전 턴과 비교한 변화량 컬럼 추가
# 정렬 (turn 기준으로 비교할 수 있도록)
df.sort_values(by=['investSessionId', 'riskLevel', 'turn'], inplace=True)

# 이전 턴과 비교한 변화량 계산
df['deltaShares'] = df.groupby(['investSessionId', 'riskLevel'])['numberOfShares'].diff()

# NaN 값을 numberOfShares 값으로 대체
df['deltaShares'] = df['deltaShares'].fillna(df['numberOfShares'])

# 정수형으로 변환
df['deltaShares'] = df['deltaShares'].astype(int)
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class,deltaShares
22,"b""BNrI\x01'\xf7ne+\xe1\x95Xg\xfe\x90""",b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,200,0,100,100,8,0,BUY,12,4,2025-06-10 13:55:56,2025-06-10 13:56:08,com.popoworld.backend.invest.entity.InvestHistory,8
24,"b""\xf7F\x8a\xacQx}\xe4\xe6\x8b6'0\xe7s\x8a""",b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,175,100,90,100,6,-20,SELL,4,6,2025-06-10 13:56:08,2025-06-10 13:56:19,com.popoworld.backend.invest.entity.InvestHistory,-2
29,b'\x86@t\x15\x8e6JC\x05\xba\x86\x7fup.\xb8',b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,high,70,90,70,100,6,0,KEEP,0,0,2025-06-10 13:56:19,2025-06-10 13:56:22,com.popoworld.backend.invest.entity.InvestHistory,0
31,b'\x19N\xa91\x83\xb3qTd|u\xf9]\x9dR\xb4',b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,high,70,70,60,100,6,0,KEEP,0,0,2025-06-10 13:56:22,2025-06-10 13:56:23,com.popoworld.backend.invest.entity.InvestHistory,0
33,b'\x9a@\x14\x01\xec\xc6L\x89\xe2\xea\xe2\x16\x...,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,high,70,60,50,100,6,0,KEEP,0,0,2025-06-10 13:56:23,2025-06-10 13:56:24,com.popoworld.backend.invest.entity.InvestHistory,0

# PostgreSQL에서 DataFrame으로 가져오기

In [153]:
import pandas as pd
from dotenv import load_dotenv
import os
import psycopg2

load_dotenv(override=True)

# PostgreSQL 연결 정보
conn = psycopg2.connect(
    host=os.getenv("DB_HOST"),
    port=os.getenv("DB_PORT"),          
    dbname=os.getenv("DB_NAME"), 
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD") 
)

# SQL 쿼리 실행 후 DataFrame으로 불러오기
s_query = "SELECT chapter_id, seed_money FROM invest_chapter;"
c_query = "SELECT user_id, sex, age FROM users;"
seed = pd.read_sql(s_query, conn)
child = pd.read_sql(c_query, conn)

# 연결 종료
conn.close()

# 결과 확인
print(seed.head())
print(child.head())

  chapter_id  seed_money
0       1111         700
1       2222        2000
2       3333        5000
3       4444       10000
                                user_id sex  age
0  58b3f430-1216-4924-9576-07f94e7f57eb   M   22
1  51945101-8208-4e63-a3bb-bdc60608a633   M   12
2  1405c1fc-2d26-441a-b088-4aa54ea73535   M   12
3  a3586f50-cd51-4d83-babd-072b12a88658   F   12
4  b79fb5ad-27bb-447c-b6ef-f4940c8b6770   F   12

/tmp/ipykernel_159422/4158424476.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seed = pd.read_sql(s_query, conn)
/tmp/ipykernel_159422/4158424476.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  child = pd.read_sql(c_query, conn)

In [ ]:
# PostgreSQL과 MongoDB의 변수명 통일
seed.rename(columns={'chapter_id': 'chapterId'}, inplace=True)
seed.rename(columns={'seed_money': 'seedMoney'}, inplace=True)
seed.head()

  chapterId  seedMoney
0      1111        700
1      2222       2000
2      3333       5000
3      4444      10000

In [155]:
# PostgreSQL과 MongoDB의 변수명 통일
child.rename(columns={'user_id':'userId'}, inplace=True)
child.head()

                                 userId sex  age
0  58b3f430-1216-4924-9576-07f94e7f57eb   M   22
1  51945101-8208-4e63-a3bb-bdc60608a633   M   12
2  1405c1fc-2d26-441a-b088-4aa54ea73535   M   12
3  a3586f50-cd51-4d83-babd-072b12a88658   F   12
4  b79fb5ad-27bb-447c-b6ef-f4940c8b6770   F   12

# 거래참여 턴 개수 (tradingTurn / investSessionId + childId)

In [156]:
tpt = df[['investSessionId', 
          'userId',
          'turn',
          'riskLevel',
          'transactionType']].copy()

tpt.head()

,investSessionId,userId,turn,riskLevel,transactionType
22,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,BUY
24,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,SELL
29,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,high,KEEP
31,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,high,KEEP
33,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,high,KEEP

In [157]:
hold_flags = tpt.groupby(['investSessionId', 'userId', 'turn'])['transactionType'].apply(lambda x: int((x != "KEEP").any())).reset_index(name="notAllKeep")
hold_flags.head()

,investSessionId,userId,turn,notAllKeep
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,1
1,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,1
2,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,1
3,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,0
4,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,0

In [158]:
tradingTurn = hold_flags.groupby(['investSessionId', 'userId'])['notAllKeep'].mean().reset_index(name="avgNotKeep")
tradingTurn.head()

,investSessionId,userId,avgNotKeep
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.428571
1,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.571429

# 거래횟수 (transactionNum / investSessionId)

In [159]:
nt = df[['investSessionId', 
          'turn',
          'riskLevel',
          'plusClick',
          'minusClick']].copy()

nt['click'] = nt['plusClick'] + nt['minusClick']

nt.head()

,investSessionId,turn,riskLevel,plusClick,minusClick,click
22,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1,high,12,4,16
24,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',2,high,4,6,10
29,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',3,high,0,0,0
31,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',4,high,0,0,0
33,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',5,high,0,0,0

In [160]:
transactionNum = nt.groupby('investSessionId')[['click']].mean().reset_index()
transactionNum.head()

                                     investSessionId     click
0     b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99'  3.285714
1  b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80'  1.761905

# 평균 현금잔여율 (averageCashRatio / investSessionId)

In [ ]:
acr = df[['investSessionId', 
          'chapterId',
          'turn',
          'currentPoint']].copy()

acr = acr.groupby(['investSessionId', 'chapterId', 'turn'])['currentPoint'].mean().reset_index(name='avgCurrentValue')

acr.head()

,investSessionId,chapterId,turn,avgCurrentValue
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,1,100.000000
1,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,2,98.333333
2,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,3,98.333333
3,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,4,96.666667
4,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,5,95.000000

In [162]:
acr_merged = acr.merge(seed, on='chapterId', how='left')
acr_merged.head()

,investSessionId,chapterId,turn,avgCurrentValue,seedMoney
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,1,100.000000,700
1,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,2,98.333333,700
2,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,3,98.333333,700
3,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,4,96.666667,700
4,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1111,5,95.000000,700

In [163]:
acr_merged['diff'] = acr_merged['seedMoney'] - acr_merged['avgCurrentValue']

averageCashRatio = acr_merged.groupby('investSessionId')['diff'].mean().reset_index(name="avgDiff")

averageCashRatio.head()

                                     investSessionId     avgDiff
0     b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99'  603.809524
1  b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80'  603.809524

# 평균 턴 체류시간 (avgStayTime / investSessionId)

In [164]:
# 평균 턴 체류시간
turn = df[['investSessionId', 
                'turn',
                'startedAt',
                'endedAt']].copy()

In [165]:
avgStayTime = turn.drop_duplicates(subset=['investSessionId', 'turn']).copy()

In [166]:
avgStayTime['stayTime'] = (avgStayTime['endedAt'] - avgStayTime['startedAt']).dt.total_seconds()
avgStayTime.drop(columns=['startedAt', 'endedAt'], inplace=True)

avgStayTime = avgStayTime.groupby('investSessionId')['stayTime'].mean().reset_index(name='avgStayTime')

# 각 위험 별 구매/판매 비율 (avgTradeRatio / InvestSessionId)

In [167]:
# 구매 데이터 생성
transcation_df = df[['investSessionId',
                     'turn',
                     'riskLevel',
                     'numberOfShares',
                     'deltaShares']].copy()

In [168]:
# 변화량에 따라 BUY/SELL 구분하기
import numpy as np

transcation_df['is_buy'] = np.where(
    transcation_df['deltaShares'] > 0, 
    transcation_df['deltaShares'], 
    0
)

transcation_df['is_sell'] = np.where(
    transcation_df['deltaShares'] < 0, 
    -transcation_df['deltaShares'],
    0
)

transcation_df.head()

,investSessionId,turn,riskLevel,numberOfShares,deltaShares,is_buy,is_sell
22,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',1,high,8,8,8,0
24,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',2,high,6,-2,0,2
29,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',3,high,6,0,0,0
31,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',4,high,6,0,0,0
33,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',5,high,6,0,0,0

In [169]:
# 각 investSessionId, riskLevel 별로 buy/sell 개수 집계
buy_sell_counts = transcation_df.groupby(['investSessionId', 'riskLevel'])[['is_buy', 'is_sell']].sum().reset_index()
buy_sell_counts.rename(columns={'is_buy': 'buyCount', 'is_sell': 'sellCount'}, inplace=True)
buy_sell_counts.head()

,investSessionId,riskLevel,buyCount,sellCount
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',high,8,2
1,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',low,7,0
2,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',mid,6,0
3,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',high,13,4
4,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',low,9,2

In [170]:
# investSessionId별 전체 buy_count, sell_count 구하기
total_buy = buy_sell_counts.groupby('investSessionId')['buyCount'].sum().reset_index(name='totalBuyCount')
total_sell = buy_sell_counts.groupby('investSessionId')['sellCount'].sum().reset_index(name='totalSellCount')

# 원본과 병합
buy_sell_counts = buy_sell_counts.merge(total_buy, on='investSessionId')
buy_sell_counts = buy_sell_counts.merge(total_sell, on='investSessionId')

buy_sell_counts['buyRatio'] = buy_sell_counts['buyCount'] / buy_sell_counts['totalBuyCount']
buy_sell_counts['sellRatio'] = buy_sell_counts['sellCount'] / buy_sell_counts['totalSellCount']

buy_sell_counts.head()

,investSessionId,riskLevel,buyCount,sellCount,totalBuyCount,totalSellCount,buyRatio,sellRatio
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',high,8,2,21,2,0.380952,1.00
1,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',low,7,0,21,2,0.333333,0.00
2,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',mid,6,0,21,2,0.285714,0.00
3,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',high,13,4,29,8,0.448276,0.50
4,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',low,9,2,29,8,0.310345,0.25

In [ ]:
# buy_ratio_pivot: 열로 riskLevel을 펼치기
buy_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='buyRatio')
buy_ratio_pivot.columns = [f"{level}BuyRatio" for level in buy_ratio_pivot.columns]
buy_ratio_pivot.reset_index(inplace=True)

# sell_ratio pivot: 열로 riskLevel을 펼치기
sell_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='sellRatio')
sell_ratio_pivot.columns = [f"{level}SellRatio" for level in sell_ratio_pivot.columns]
sell_ratio_pivot.reset_index(inplace=True)

# merge 두 pivot
avgTradeRatio = pd.merge(buy_ratio_pivot, sell_ratio_pivot, on='investSessionId')

avgTradeRatio.head()

,investSessionId,highBuyRatio,lowBuyRatio,midBuyRatio,highSellRatio,lowSellRatio,midSellRatio
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',0.380952,0.333333,0.285714,1.0,0.00,0.00
1,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',0.448276,0.310345,0.241379,0.5,0.25,0.25

# 평균 tag 뉴스 발생 턴 체류 시간 (tagAvgStayTime / investSessionId)

In [130]:
tag_turn_df = df[['investSessionId',
           'turn',
           'newsTag',
           'startedAt',
           'endedAt']].drop_duplicates()

tag_turn_df = tag_turn_df[tag_turn_df['newsTag'] != "all"]
tag_turn_df["turnDuration"] = tag_turn_df["endedAt"] = tag_turn_df["startedAt"]

tagAvgStayTime = tag_turn_df.groupby("investSessionId")["turnDuration"].mean().reset_index().rename(columns={"turnDuration":"tagTrunDuraion"})
tagAvgStayTime

KeyError: "['newsTag'] not in index"

# 위험 감수율 (riskTaking / investSessionId)

In [42]:
risk_taking = df[["investSessionId",
                  "turn",
                  "newsTag",
                  "riskLevel",
                  "numberOfShares", 
                  "transactionType", 
                  "beforeValue",
                  "currentValue",
                  "income"]].copy()
risk_taking

KeyError: "['newsTag'] not in index"

In [43]:
import numpy

conditions = [
    (df["newsTag"]=="high") & (df["riskLevel"]=="고위험 고수익"),
    (df["newsTag"]=="mid") & (df["riskLevel"]=="균형형"),
    (df["newsTag"]=="all")
]

# 각 조건별 입력할 위험 발생률률
risk = [
    0.5,
    0.3,
    0
]

# riskRatio 값 입력
risk_taking["riskRatio"] = np.nan
risk_taking["riskRatio"] = np.select(conditions, risk, default=np.nan)

# 턴별 위험 감수율 계산 (tag 종목 구매 수량 * riskRatio)
risk_taking["risktaking"] = risk_taking["numberOfShares"] * risk_taking["riskRatio"]

# 게임별 평균 위험 감수율? 총 위험감수율?
riskTaking = risk_taking.groupby("investSessionId")["risktaking"].mean().reset_index()
riskTaking

KeyError: 'newsTag'

# 배팅

# 전체 병합

In [172]:
merged = tradingTurn.merge(transactionNum, on='investSessionId', how='inner').merge(averageCashRatio, on='investSessionId', how='inner').merge(avgStayTime, on='investSessionId', how='inner').merge(avgTradeRatio, on='investSessionId', how='inner') #.merge(tagAvgStayTime, on='investSessionId', how='inner').merge(riskTaking, on='investSessionId', how='inner')
merged.head()

,investSessionId,userId,avgNotKeep,click,avgDiff,avgStayTime,highBuyRatio,lowBuyRatio,midBuyRatio,highSellRatio,lowSellRatio,midSellRatio
0,b'BK8G\xda\x03\x1e\xe3\xf4\x16o\x97I\x88S\x99',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.428571,3.285714,603.809524,4.285714,0.380952,0.333333,0.285714,1.0,0.00,0.00
1,b'LIzf\x1c\x0e\x13\x1c\xa7\x01\xee\xc8\x88G2\x80',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.571429,1.761905,603.809524,3.714286,0.448276,0.310345,0.241379,0.5,0.25,0.25

In [173]:
merged_with_userId = merged.merge(child, on="userId", how="inner")
merged_with_userId.head()

Empty DataFrame
Columns: [investSessionId, userId, avgNotKeep, click, avgDiff, avgStayTime, highBuyRatio, lowBuyRatio, midBuyRatio, highSellRatio, lowSellRatio, midSellRatio, sex, age]
Index: []