# 투자 성향 클러스터링
- invest_session_id 
- child_id 
- sex 
- age 
- chapter_id
- trade_participation_turn (거래 참여 턴 개수)
- num_of_transaction (거래 횟수, +/- 클릭 횟수)
- avg_cash_ratio (평균 현금잔여율)
- turn_dwell_time (평균 턴 체류시간)
- buy_sell_ratio (고/중/저 구매/판매 비율)
- tag_turn_dwell_time (평균 tag 뉴스 발생 턴 체류시간)
- risk_tolerance (위험 감수율)
- bet_success_rate (배팅 성공율)

Child (PostgreSQL)
- child_id
- sex
- age

InvestHistory (MongoDB)
- invest_session_id
- chapter_id
- child_id
- turn
- risk_level
- current_point
- before_value
- current_value
- initial_value
- number_of_shares
- income
- transaction_type
tag추가

# MongoDB에서 바로 DataFrame으로 가져오기

In [242]:
from pymongo import MongoClient
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv(override=True)

# MongoDB 연결 정보
uri = os.getenv("MONGO_URI")
db_name = os.getenv("MONGO_DB_NAME")
collection_name = os.getenv("COLLECTION_NAME")

client = MongoClient(uri)
db = client[db_name]
collection = db[collection_name]

# MongoDB에서 데이터 불러오기
data = list(collection.find())

# DataFrame으로 변환
df = pd.DataFrame(data)
df.head()

Empty DataFrame
Columns: []
Index: []

In [190]:
# 현재는 mongoDB에 childId라고 저장이 되어있는데 나중에 userId로 바뀔 예정이기 때문에 바꾸는 과정 추가해둠
### 나중에 삭제 될 코드
df.rename(columns={'childId':'userId'}, inplace=True)
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class,newsTag
0,b'\xe5M\xcc@\x1e\xb8W\xbd\xfd6\xc2\x06\xc2\xb8...,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,고위험 고수익,600,0,100,100,5,0,BUY,5,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
1,b'\xfc@\xb0\x89\x87^g\xe0\x82\xd2*\x99|?\xe2\x81',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,중위험 균형형,600,0,100,100,4,0,BUY,4,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
2,b'\xa5Mt\xd7c\x8d\xe4\x9f\xaf!\xa78\xef\x9b\x9...,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,저위험 저수익,600,0,100,100,5,0,BUY,5,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
3,b'<H\xe6\x9e\xce\x87\xba1\xee\xf0\x81\xc4#og\x86',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,고위험 고수익,478,100,101,100,5,0,KEEP,0,0,2025-06-12 13:20:54,2025-06-12 13:21:00,com.popoworld.backend.invest.child.entity.Inve...,all
4,b'\x17BJ\xb6*\xd6i\xa2W\xac\xa7\xefs^O\x9d',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,중위험 균형형,478,100,108,100,7,0,BUY,5,2,2025-06-12 13:20:54,2025-06-12 13:21:00,com.popoworld.backend.invest.child.entity.Inve...,all

In [191]:
# riskLevel 한영변환
df['riskLevel'] = df['riskLevel'].replace({
    '고위험 고수익' : 'high',
    '중위험 균형형' : 'mid',
    '저위험 저수익' : 'low'
})
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class,newsTag
0,b'\xe5M\xcc@\x1e\xb8W\xbd\xfd6\xc2\x06\xc2\xb8...,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,600,0,100,100,5,0,BUY,5,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
1,b'\xfc@\xb0\x89\x87^g\xe0\x82\xd2*\x99|?\xe2\x81',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,mid,600,0,100,100,4,0,BUY,4,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
2,b'\xa5Mt\xd7c\x8d\xe4\x9f\xaf!\xa78\xef\x9b\x9...,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,low,600,0,100,100,5,0,BUY,5,0,2025-06-12 13:20:42,2025-06-12 13:20:54,com.popoworld.backend.invest.child.entity.Inve...,NaN
3,b'<H\xe6\x9e\xce\x87\xba1\xee\xf0\x81\xc4#og\x86',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,478,100,101,100,5,0,KEEP,0,0,2025-06-12 13:20:54,2025-06-12 13:21:00,com.popoworld.backend.invest.child.entity.Inve...,all
4,b'\x17BJ\xb6*\xd6i\xa2W\xac\xa7\xefs^O\x9d',b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,mid,478,100,108,100,7,0,BUY,5,2,2025-06-12 13:20:54,2025-06-12 13:21:00,com.popoworld.backend.invest.child.entity.Inve...,all

In [192]:
# 파생 변수 : 이전 턴과 비교한 종목 수량 변화량 컬럼 추가
# 정렬 (turn 기준으로 비교할 수 있도록)
df.sort_values(by=['investSessionId', 'riskLevel', 'turn'], inplace=True)

# 이전 턴과 비교한 변화량 계산
df['deltaShares'] = df.groupby(['investSessionId', 'riskLevel'])['numberOfShares'].diff()

# NaN 값을 numberOfShares 값으로 대체
df['deltaShares'] = df['deltaShares'].fillna(df['numberOfShares'])

# 정수형으로 변환
df['deltaShares'] = df['deltaShares'].astype(int)
df.head()

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,numberOfShares,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class,newsTag,deltaShares
33,b'.J\xf4\xa0\xd5&x\\\x1d\x99|r\xc5\xa5}\x99',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,1300,0,100,100,3,0,BUY,3,0,2025-06-12 13:37:10,2025-06-12 13:38:34,com.popoworld.backend.invest.child.entity.Inve...,NaN,3
38,b'!E\xd7\xbb\rM\xd3\xb9\xb29\n\x1a{u{\xa7',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,2021,100,101,100,0,3,SELL,0,3,2025-06-12 13:38:34,2025-06-12 13:39:03,com.popoworld.backend.invest.child.entity.Inve...,all,-3
40,b'\xbbM\x01\xedy\xfd\xa5Z\x86\xe2\xd6k-1\xe3\x8b',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,high,509,101,93,100,3,0,BUY,3,0,2025-06-12 13:39:03,2025-06-12 13:39:28,com.popoworld.backend.invest.child.entity.Inve...,high,3
44,b'\x89NNR)p\xa7\xe5;\x98\x00\xb7BF\xea\xa4',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,high,1110,93,78,100,6,0,BUY,3,0,2025-06-12 13:39:28,2025-06-12 13:39:34,com.popoworld.backend.invest.child.entity.Inve...,all,3
45,b'\xb0@\x9f\xe3\xca\xf8T\xbf1A\x16\x01\xb3\xa6...,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,high,924,78,86,100,8,0,BUY,2,0,2025-06-12 13:39:34,2025-06-12 13:39:48,com.popoworld.backend.invest.child.entity.Inve...,mid,2

# PostgreSQL에서 DataFrame으로 가져오기

In [193]:
import pandas as pd
from dotenv import load_dotenv
import os
import psycopg2

load_dotenv(override=True)

# PostgreSQL 연결 정보
conn = psycopg2.connect(
    host=os.getenv("DB_HOST"),
    port=os.getenv("DB_PORT"),          
    dbname=os.getenv("DB_NAME"), 
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD") 
)

# SQL 쿼리 실행 후 DataFrame으로 불러오기
s_query = "SELECT chapter_id, seed_money FROM invest_chapter;"
c_query = "SELECT user_id, sex, age FROM users;"
seed = pd.read_sql(s_query, conn)
child = pd.read_sql(c_query, conn)

# 연결 종료
conn.close()

# 결과 확인
print(seed.head())
print(child.head())

  chapter_id  seed_money
0       1111         700
1       2222        2000
2       3333        5000
3       4444       10000
                                user_id sex  age
0  58b3f430-1216-4924-9576-07f94e7f57eb   M   22
1  51945101-8208-4e63-a3bb-bdc60608a633   M   12
2  1405c1fc-2d26-441a-b088-4aa54ea73535   M   12
3  a3586f50-cd51-4d83-babd-072b12a88658   F   12
4  b79fb5ad-27bb-447c-b6ef-f4940c8b6770   F   12

C:\Users\user\AppData\Local\Temp\ipykernel_7440\4158424476.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seed = pd.read_sql(s_query, conn)
C:\Users\user\AppData\Local\Temp\ipykernel_7440\4158424476.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  child = pd.read_sql(c_query, conn)

In [194]:
# PostgreSQL과 MongoDB의 변수명 통일
seed.rename(columns={'chapter_id': 'chapterId'}, inplace=True)
seed.rename(columns={'seed_money': 'seedMoney'}, inplace=True)
seed.head()

  chapterId  seedMoney
0      1111        700
1      2222       2000
2      3333       5000
3      4444      10000

In [195]:
# PostgreSQL과 MongoDB의 변수명 통일
child.rename(columns={'user_id':'userId'}, inplace=True)
child.head()

                                 userId sex  age
0  58b3f430-1216-4924-9576-07f94e7f57eb   M   22
1  51945101-8208-4e63-a3bb-bdc60608a633   M   12
2  1405c1fc-2d26-441a-b088-4aa54ea73535   M   12
3  a3586f50-cd51-4d83-babd-072b12a88658   F   12
4  b79fb5ad-27bb-447c-b6ef-f4940c8b6770   F   12

# 거래참여 턴 개수 (tradingTurn / investSessionId + childId)

In [196]:
tpt = df[['investSessionId', 
          'userId',
          'turn',
          'riskLevel',
          'transactionType']].copy()

tpt.head()

,investSessionId,userId,turn,riskLevel,transactionType
33,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,BUY
38,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,SELL
40,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,high,BUY
44,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,high,BUY
45,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,high,BUY

In [197]:
hold_flags = tpt.groupby(['investSessionId', 'userId', 'turn'])['transactionType'].apply(lambda x: int((x != "KEEP").any())).reset_index(name="notAllKeep")
hold_flags.head()

,investSessionId,userId,turn,notAllKeep
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,1
1,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,1
2,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,1
3,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,1
4,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,1

In [198]:
tradingTurn = hold_flags.groupby(['investSessionId', 'userId'])['notAllKeep'].mean().reset_index(name="avgNotKeep")
tradingTurn.head()

,investSessionId,userId,avgNotKeep
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.833333
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1.000000
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000

# 거래횟수 (transactionNum / investSessionId)

In [199]:
nt = df[['investSessionId', 
          'turn',
          'riskLevel',
          'plusClick',
          'minusClick']].copy()

nt['click'] = nt['plusClick'] + nt['minusClick']

nt.head()

,investSessionId,turn,riskLevel,plusClick,minusClick,click
33,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1,high,3,0,3
38,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',2,high,0,3,3
40,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',3,high,3,0,3
44,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',4,high,3,0,3
45,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',5,high,2,0,2

In [200]:
transactionNum = nt.groupby('investSessionId')[['click']].mean().reset_index()
transactionNum.head()

                                     investSessionId     click
0     b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba'  2.777778
1           b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b'  0.000000
2  b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...  0.000000
3        b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c'  3.111111
4    b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96'  0.000000

# 평균 현금잔여율 (averageCashRatio / investSessionId)

In [201]:
acr = df[['investSessionId', 
          'chapterId',
          'turn',
          'currentPoint']].copy()

acr = acr.groupby(['investSessionId', 'chapterId', 'turn'])['currentPoint'].mean().reset_index(name='avgCurrentValue')

acr.head()

,investSessionId,chapterId,turn,avgCurrentValue
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,1,1300.0
1,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,2,2021.0
2,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,3,509.0
3,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,4,1110.0
4,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,5,924.0

In [202]:
acr_merged = acr.merge(seed, on='chapterId', how='left')
acr_merged.head()

,investSessionId,chapterId,turn,avgCurrentValue,seedMoney
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,1,1300.0,700
1,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,2,2021.0,700
2,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,3,509.0,700
3,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,4,1110.0,700
4,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,5,924.0,700

In [203]:
acr_merged['diff'] = acr_merged['seedMoney'] - acr_merged['avgCurrentValue']

averageCashRatio = acr_merged.groupby('investSessionId')['diff'].mean().reset_index(name="avgDiff")

averageCashRatio.head()

                                     investSessionId      avgDiff
0     b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba'  -431.333333
1           b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b' -1300.000000
2  b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e... -1300.000000
3        b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c'   340.000000
4    b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96' -1300.000000

# 평균 턴 체류시간 (avgStayTime / investSessionId)

In [204]:
# 평균 턴 체류시간
turn = df[['investSessionId', 
                'turn',
                'startedAt',
                'endedAt']].copy()

In [205]:
avgStayTime = turn.drop_duplicates(subset=['investSessionId', 'turn']).copy()

In [206]:
avgStayTime['stayTime'] = (avgStayTime['endedAt'] - avgStayTime['startedAt']).dt.total_seconds()
avgStayTime.drop(columns=['startedAt', 'endedAt'], inplace=True)

avgStayTime = avgStayTime.groupby('investSessionId')['stayTime'].mean().reset_index(name='avgStayTime')

# 각 위험 별 구매/판매 비율 (avgTradeRatio / InvestSessionId)

In [207]:
# 구매 데이터 생성
transcation_df = df[['investSessionId',
                     'turn',
                     'riskLevel',
                     'numberOfShares',
                     'deltaShares']].copy()

In [208]:
# 변화량에 따라 BUY/SELL 구분하기
import numpy as np

transcation_df['is_buy'] = np.where(
    transcation_df['deltaShares'] > 0, 
    transcation_df['deltaShares'], 
    0
)

transcation_df['is_sell'] = np.where(
    transcation_df['deltaShares'] < 0, 
    -transcation_df['deltaShares'],
    0
)

transcation_df.head()

,investSessionId,turn,riskLevel,numberOfShares,deltaShares,is_buy,is_sell
33,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1,high,3,3,3,0
38,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',2,high,0,-3,0,3
40,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',3,high,3,3,3,0
44,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',4,high,6,3,3,0
45,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',5,high,8,2,2,0

In [209]:
# 각 investSessionId, riskLevel 별로 buy/sell 개수 집계
buy_sell_counts = transcation_df.groupby(['investSessionId', 'riskLevel'])[['is_buy', 'is_sell']].sum().reset_index()
buy_sell_counts.rename(columns={'is_buy': 'buyCount', 'is_sell': 'sellCount'}, inplace=True)
buy_sell_counts.head()

,investSessionId,riskLevel,buyCount,sellCount
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',high,11,3
1,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',low,5,5
2,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',mid,13,9
3,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',high,0,0
4,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',low,0,0

In [210]:
# investSessionId별 전체 buy_count, sell_count 구하기
total_buy = buy_sell_counts.groupby('investSessionId')['buyCount'].sum().reset_index(name='totalBuyCount')
total_sell = buy_sell_counts.groupby('investSessionId')['sellCount'].sum().reset_index(name='totalSellCount')

# 원본과 병합
buy_sell_counts = buy_sell_counts.merge(total_buy, on='investSessionId')
buy_sell_counts = buy_sell_counts.merge(total_sell, on='investSessionId')

buy_sell_counts['buyRatio'] = buy_sell_counts['buyCount'] / buy_sell_counts['totalBuyCount']
buy_sell_counts['sellRatio'] = buy_sell_counts['sellCount'] / buy_sell_counts['totalSellCount']

buy_sell_counts

,investSessionId,riskLevel,buyCount,sellCount,totalBuyCount,totalSellCount,buyRatio,sellRatio
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',high,11,3,29,17,0.379310,0.176471
1,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',low,5,5,29,17,0.172414,0.294118
2,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',mid,13,9,29,17,0.448276,0.529412
3,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',high,0,0,0,0,NaN,NaN
4,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',low,0,0,0,0,NaN,NaN
5,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',mid,0,0,0,0,NaN,NaN
6,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,high,0,0,0,0,NaN,NaN
7,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,low,0,0,0,0,NaN,NaN
8,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,mid,0,0,0,0,NaN,NaN
9,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',high,9,0,22,2,0.409091,0.000000
10,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',low,5,2,22,2,0.227273,1.000000
11,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',mid,8,0,22,2,0.363636,0.000000
12,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',high,0,0,0,0,NaN,NaN
13,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',low,0,0,0,0,NaN,NaN
14,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',mid,0,0,0,0,NaN,NaN
15,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,high,0,0,0,0,NaN,NaN
16,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,low,0,0,0,0,NaN,NaN
17,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,mid,0,0,0,0,NaN,NaN
18,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,high,12,10,56,44,0.214286,0.227273
19,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,low,32,29,56,44,0.571429,0.659091
20,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,mid,12,5,56,44,0.214286,0.113636

In [211]:
# buy_ratio_pivot: 열로 riskLevel을 펼치기
buy_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='buyRatio')
buy_ratio_pivot.columns = [f"{level}BuyRatio" for level in buy_ratio_pivot.columns]
buy_ratio_pivot.reset_index(inplace=True)

# sell_ratio pivot: 열로 riskLevel을 펼치기
sell_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='sellRatio')
sell_ratio_pivot.columns = [f"{level}SellRatio" for level in sell_ratio_pivot.columns]
sell_ratio_pivot.reset_index(inplace=True)

# merge 두 pivot
avgTradeRatio = pd.merge(buy_ratio_pivot, sell_ratio_pivot, on='investSessionId')

avgTradeRatio.head()

,investSessionId,highBuyRatio,lowBuyRatio,midBuyRatio,highSellRatio,lowSellRatio,midSellRatio
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',0.379310,0.172414,0.448276,0.176471,0.294118,0.529412
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',NaN,NaN,NaN,NaN,NaN,NaN
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,NaN,NaN,NaN,NaN,NaN,NaN
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',0.409091,0.227273,0.363636,0.000000,1.000000,0.000000
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',NaN,NaN,NaN,NaN,NaN,NaN

# 평균 tag 뉴스 발생 턴 체류 시간 (tagAvgStayTime / investSessionId)

In [212]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 33 to 27
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              93 non-null     object
 1   investSessionId  93 non-null     object
 2   chapterId        93 non-null     object
 3   userId           93 non-null     object
 4   turn             93 non-null     int64
 5   riskLevel        93 non-null     object
 6   currentPoint     93 non-null     int64
 7   beforeValue      93 non-null     int64
 8   currentValue     93 non-null     int64
 9   initialValue     93 non-null     int64
 10  numberOfShares   93 non-null     int64
 11  income           93 non-null     int64
 12  transactionType  93 non-null     object
 13  plusClick        93 non-null     int64
 14  minusClick       93 non-null     int64
 15  startedAt        93 non-null     datetime64[ns]
 16  endedAt          93 non-null     datetime64[ns]
 17  _class           93 non-null     object
 18  newsTag          72 non-null     object
 19  deltaShares      93 non-null     int32
dtypes: datetime64[ns](2), int32(1), int64(9), object(8)
memory usage: 14.9+ KB

In [213]:
import numpy as np
import random

# 1. 고유한 userId 목록 추출
unique_user_ids = df['userId'].unique()

# 2. 각 고유 userId에 대해 무작위 나이 생성
# np.random.randint를 사용하여 필요한 개수만큼 나이 생성
random_ages = np.random.randint(3, 13 + 1, size=len(unique_user_ids))

# 3. userId와 무작위 나이 매핑 딕셔너리 생성
user_age_map = dict(zip(unique_user_ids, random_ages))

print("\n--- 생성된 userId-age 매핑 ---")
print(user_age_map)

# 4. .map() 함수를 사용하여 DataFrame에 나이 할당
df['age'] = df['userId'].map(user_age_map)

print("\n--- 각 고유 userId에 일관된 무작위 나이 할당 후 ---")

df

--- 생성된 userId-age 매핑 ---
{Binary(b'33""\x11\x11\x11\xc1UUUUUUDD', 3): 12}

--- 각 고유 userId에 일관된 무작위 나이 할당 후 ---

,_id,investSessionId,chapterId,userId,turn,riskLevel,currentPoint,beforeValue,currentValue,initialValue,...,income,transactionType,plusClick,minusClick,startedAt,endedAt,_class,newsTag,deltaShares,age
33,b'.J\xf4\xa0\xd5&x\\\x1d\x99|r\xc5\xa5}\x99',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1,high,1300,0,100,100,...,0,BUY,3,0,2025-06-12 13:37:10,2025-06-12 13:38:34,com.popoworld.backend.invest.child.entity.Inve...,NaN,3,12
38,b'!E\xd7\xbb\rM\xd3\xb9\xb29\n\x1a{u{\xa7',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",2,high,2021,100,101,100,...,3,SELL,0,3,2025-06-12 13:38:34,2025-06-12 13:39:03,com.popoworld.backend.invest.child.entity.Inve...,all,-3,12
40,b'\xbbM\x01\xedy\xfd\xa5Z\x86\xe2\xd6k-1\xe3\x8b',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,high,509,101,93,100,...,0,BUY,3,0,2025-06-12 13:39:03,2025-06-12 13:39:28,com.popoworld.backend.invest.child.entity.Inve...,high,3,12
44,b'\x89NNR)p\xa7\xe5;\x98\x00\xb7BF\xea\xa4',b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,high,1110,93,78,100,...,0,BUY,3,0,2025-06-12 13:39:28,2025-06-12 13:39:34,com.popoworld.backend.invest.child.entity.Inve...,all,3,12
45,b'\xb0@\x9f\xe3\xca\xf8T\xbf1A\x16\x01\xb3\xa6...,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,high,924,78,86,100,...,0,BUY,2,0,2025-06-12 13:39:34,2025-06-12 13:39:48,com.popoworld.backend.invest.child.entity.Inve...,mid,2,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,b'\xd9D5\xbe\xe2\x1bY\xdc\x8au\xcf)]5\x98\x9a',b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",3,mid,82,108,112,100,...,0,KEEP,0,0,2025-06-12 13:28:04,2025-06-12 13:28:09,com.popoworld.backend.invest.child.entity.Inve...,high,0,12
19,b'bH\xec\xe4\x89\xa6\xe3\xe0\xb1\x83\xe4e\xf3\...,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",4,mid,1642,112,113,100,...,0,KEEP,0,0,2025-06-12 13:28:09,2025-06-12 13:28:13,com.popoworld.backend.invest.child.entity.Inve...,mid,0,12
22,b'\x96F\xd25d\xf0\xf6xq\xf8\x9c\x0c+\x1d\xe1\xbc',b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",5,mid,87,113,121,100,...,0,BUY,5,0,2025-06-12 13:28:13,2025-06-12 13:28:18,com.popoworld.backend.invest.child.entity.Inve...,all,5,12
25,b'`Nktk\x06\x81\xad\x9dG\xca_$|\xc0\xad',b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",6,mid,1724,121,125,100,...,32,SELL,0,4,2025-06-12 13:28:18,2025-06-12 13:28:23,com.popoworld.backend.invest.child.entity.Inve...,high,-4,12
27,b'xEWA7\xcc\xd3\x0c$C2\xe7\x95~\x11\x97',b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,1111,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",7,mid,770,125,126,100,...,0,BUY,5,0,2025-06-12 13:28:23,2025-06-12 13:28:26,com.popoworld.backend.invest.child.entity.Inve...,,5,12

In [214]:
tag_turn_df = df[['investSessionId',
           'turn',
           'newsTag',
           'startedAt',
           'endedAt', 'userId', 'age']].drop_duplicates()

tag_turn_df = tag_turn_df[tag_turn_df['newsTag'] != "all"]
tag_turn_df["turnDuration"] = tag_turn_df["endedAt"] - tag_turn_df["startedAt"]

tagAvgStayTime = tag_turn_df.groupby(["investSessionId","userId",'age'])["turnDuration"].mean().reset_index().rename(columns={"turnDuration":"tagTrunDuraion"})
tagAvgStayTime

,investSessionId,userId,age,tagTrunDuraion
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:32
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:03
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:10
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:27.500000
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:03:20
5,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:02:29.600000
6,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:04.800000

In [215]:
data = tagAvgStayTime
col = "tagTrunDuraion"

col_mean = data.groupby("age")[f"{col}"].mean()
col_mean

age
12   0 days 00:01:00.985714285
Name: tagTrunDuraion, dtype: timedelta64[ns]

In [216]:
data[f'{col}Mean'] = data['age'].map(col_mean)
data

,investSessionId,userId,age,tagTrunDuraion,tagTrunDuraionMean
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:32,0 days 00:01:00.985714285
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:03,0 days 00:01:00.985714285
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:10,0 days 00:01:00.985714285
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:27.500000,0 days 00:01:00.985714285
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:03:20,0 days 00:01:00.985714285
5,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:02:29.600000,0 days 00:01:00.985714285
6,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:04.800000,0 days 00:01:00.985714285

In [217]:

def chart_mean(df, col):

    col_mean = df.groupby("age")[f"{col}"].mean()
    df[f'{col}Mean'] = df['age'].map(col_mean)

    return df

chart_mean(tagAvgStayTime, "tagTrunDuraion")

,investSessionId,userId,age,tagTrunDuraion,tagTrunDuraionMean
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:32,0 days 00:01:00.985714285
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:03,0 days 00:01:00.985714285
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:10,0 days 00:01:00.985714285
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:27.500000,0 days 00:01:00.985714285
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:03:20,0 days 00:01:00.985714285
5,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:02:29.600000,0 days 00:01:00.985714285
6,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",12,0 days 00:00:04.800000,0 days 00:01:00.985714285

# 위험 감수율 (betMidShares, betHighShares / investSessionId)
- 중위험 tag 발생 시 중위험 종목 구매 수량
- 고위험 tag 발생 시 고위험 종목 구매 수량

In [218]:
bet_data = df[["investSessionId","turn","newsTag","riskLevel","numberOfShares","deltaShares", "transactionType", "beforeValue","currentValue","income"]].copy()

# newsTag 발생 시 해당 종목을 구매한 경우
bet_buy = bet_data.loc[(bet_data["newsTag"] == bet_data["riskLevel"]) & (bet_data["transactionType"]=="BUY")]

bet_mid = bet_buy[bet_buy["riskLevel"]=="mid"].groupby("investSessionId")["deltaShares"].sum().reset_index().rename(columns={"deltaShares":"betMidShares"})
bet_high = bet_buy[bet_buy["riskLevel"]=="high"].groupby("investSessionId")["deltaShares"].sum().reset_index().rename(columns={"deltaShares":"betHighShares"})


risk_taking = pd.merge(bet_mid, bet_high, on="investSessionId", how="outer")

# nan 인 값들은 0으로 채우기
risk_taking.fillna(0)

                                  investSessionId  betMidShares  betHighShares
0  b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba'           2.0              3
1     b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c'           0.0              4

# 베팅 성공률 (betBuyRatio, betSellRatio / investSessionId)
: 베팅 성공률
1) 구매 베팅 성공 = tag뉴스 발생 턴에서 해당 종목 구매 후 다음 턴에서 가격이 증가한 횟수 / tag 뉴스 발생턴에서 해당 종목을 구매한 횟수
2) 판매 베팅 성공 = tag뉴스 발생 턴에서 해당 종목 판매 후 다음 턴에서 가격이 감소한 횟수 / tag 뉴스 발생턴에서 해당 종목을 판매한 횟수

In [219]:
# 구매 베팅 성공
bet_win = df[["investSessionId","turn","newsTag","riskLevel","beforeValue","currentValue", "transactionType"]].copy()

# 다음 턴의 value 컬럼 구하기
bet_win.sort_values(by=["investSessionId","riskLevel","turn"], inplace=True)
bet_win["nextValue"] = bet_win["currentValue"].shift(-1)

# tag 뉴스 턴에서 해당 종목을 구매한 횟수
bet_buy = bet_win.loc[(bet_win["newsTag"]==bet_win["riskLevel"]) & (bet_win["transactionType"]=="BUY")].copy()
bet_buy_total = bet_buy.groupby("investSessionId")["nextValue"].count().reset_index().rename(columns={"nextValue":"bet_buy_total"})

# tag 뉴스 턴에서 해당 종목을 구매하고 다음 턴에서 가격이 오른 횟수
bet_buy["value_diff"] = bet_buy["nextValue"] - bet_buy["currentValue"]
bet_buy_win = bet_buy[bet_buy["value_diff"]>0]
bet_buy_win = bet_buy_win.groupby("investSessionId")["value_diff"].count().reset_index().rename(columns={"value_diff":"bet_buy_win"})

# 성공 비율 계산
bet_buy_df = pd.merge(bet_buy_total, bet_buy_win, on="investSessionId", how="left")
bet_buy_df["betBuyRatio"] = bet_buy_df["bet_buy_win"] / bet_buy_df["bet_buy_total"]

# nan값 0으로 채우기
bet_buy_df = bet_buy_df.fillna(0) # 데이터가 없어서 nan으로 출력됨..! 0으로 채워주기기

# 필요없는 컬럼 삭제
bet_buy_df.drop(columns=["bet_buy_total","bet_buy_win"], inplace=True)
bet_buy_df

                                  investSessionId  betBuyRatio
0  b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba'          0.5
1     b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c'          1.0

In [220]:
# 판매 베팅 성공

# tag 뉴스 턴에서 해당 종목을 판매한 횟수
bet_sell = bet_win.loc[(bet_win["newsTag"]==bet_win["riskLevel"]) & (bet_win["transactionType"]=="SELL")].copy()
bet_sell_total = bet_sell.groupby("investSessionId")["nextValue"].count().reset_index().rename(columns={"nextValue":"bet_sell_total"})

# tag 뉴스 턴에서 해당 종목을 구매하고 다음 턴에서 가격이 오른 횟수
bet_sell["value_diff"] = bet_sell["nextValue"] - bet_sell["currentValue"]
bet_sell_win = bet_sell[bet_sell["value_diff"]<0]
bet_sell_win = bet_sell_win.groupby("investSessionId")["value_diff"].count().reset_index().rename(columns={"value_diff":"bet_sell_win"})


# 성공 비율 계산
bet_sell_df = pd.merge(bet_sell_total, bet_sell_win, on="investSessionId", how="left")
bet_sell_df["betSellRatio"] = bet_sell_df["bet_sell_win"] / bet_sell_df["bet_sell_total"]

# nan값 0으로 채우기
bet_sell_df = bet_sell_df.fillna(0) # 데이터가 없어서 nan으로 출력됨..! 0으로 채워주기기

# 필요없는 컬럼 삭제
bet_sell_df.drop(columns=["bet_sell_total","bet_sell_win"], inplace=True)
bet_sell_df

                                     investSessionId  betSellRatio
0  b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...           0.0

# 전체 병합

In [221]:
merged = tradingTurn.merge(transactionNum, on='investSessionId', how='inner').merge(averageCashRatio, on='investSessionId', how='inner').merge(avgStayTime, on='investSessionId', how='inner').merge(avgTradeRatio, on='investSessionId', how='inner') #.merge(tagAvgStayTime, on='investSessionId', how='inner').merge(riskTaking, on='investSessionId', how='inner')
merged.head()

,investSessionId,userId,avgNotKeep,click,avgDiff,avgStayTime,highBuyRatio,lowBuyRatio,midBuyRatio,highSellRatio,lowSellRatio,midSellRatio
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.833333,2.777778,-431.333333,27.166667,0.379310,0.172414,0.448276,0.176471,0.294118,0.529412
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000,0.000000,-1300.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000,0.000000,-1300.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",1.000000,3.111111,340.000000,20.333333,0.409091,0.227273,0.363636,0.000000,1.000000,0.000000
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',"b'33""""\x11\x11\x11\xc1UUUUUUDD'",0.000000,0.000000,-1300.000000,143.285714,NaN,NaN,NaN,NaN,NaN,NaN

In [222]:
merged_with_userId = merged.merge(child, on="userId", how="inner")
merged_with_userId.head()

Empty DataFrame
Columns: [investSessionId, userId, avgNotKeep, click, avgDiff, avgStayTime, highBuyRatio, lowBuyRatio, midBuyRatio, highSellRatio, lowSellRatio, midSellRatio, sex, age]
Index: []

In [235]:
import numpy as np
import pandas as pd

# 각 위험 별 구매/판매 비율
def avg_trade_ratio(df):
    # 구매 데이터 생성
    transcation_df = df[['investSessionId',
                        'turn',
                        'riskLevel',
                        'numberOfShares',
                        'deltaShares', "userId"]]
    
    # 변화량에 따라 BUY/SELL 구분하기
    transcation_df['is_buy'] = np.where(
        transcation_df['deltaShares'] > 0, 
        transcation_df['deltaShares'], 
        0
    )

    transcation_df['is_sell'] = np.where(
        transcation_df['deltaShares'] < 0, 
        -transcation_df['deltaShares'],
        0
    )

    # 각 investSessionId, riskLevel 별로 buy/sell 개수 집계
    buy_sell_counts = transcation_df.groupby(['investSessionId', 'riskLevel'])[['is_buy', 'is_sell']].sum().reset_index()
    buy_sell_counts.rename(columns={'is_buy': 'buyCount', 'is_sell': 'sellCount'}, inplace=True)
    buy_sell_counts.head()

    # investSessionId별 전체 buy_count, sell_count 구하기
    total_buy = buy_sell_counts.groupby('investSessionId')['buyCount'].sum().reset_index(name='totalBuyCount')
    total_sell = buy_sell_counts.groupby('investSessionId')['sellCount'].sum().reset_index(name='totalSellCount')

    # 원본과 병합
    buy_sell_counts = buy_sell_counts.merge(total_buy, on='investSessionId')
    buy_sell_counts = buy_sell_counts.merge(total_sell, on='investSessionId')

    buy_sell_counts['buyRatio'] = buy_sell_counts['buyCount'] / buy_sell_counts['totalBuyCount']
    buy_sell_counts['sellRatio'] = buy_sell_counts['sellCount'] / buy_sell_counts['totalSellCount']

    buy_sell_counts.head()

    # buy_ratio_pivot: 열로 riskLevel을 펼치기  
    buy_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='buyRatio')
    buy_ratio_pivot = buy_ratio_pivot.fillna(0)
    buy_ratio_pivot.columns = [f"{level}BuyRatio" for level in buy_ratio_pivot.columns]
    buy_ratio_pivot.reset_index(inplace=True)

    # sell_ratio pivot: 열로 riskLevel을 펼치기
    sell_ratio_pivot = buy_sell_counts.pivot(index='investSessionId', columns='riskLevel', values='sellRatio')
    sell_ratio_pivot = sell_ratio_pivot.fillna(0)
    sell_ratio_pivot.columns = [f"{level}SellRatio" for level in sell_ratio_pivot.columns]
    sell_ratio_pivot.reset_index(inplace=True)

    # merge 두 pivot
    avgTradeRatio = pd.merge(buy_ratio_pivot, sell_ratio_pivot, on='investSessionId')

    user_info = transcation_df.groupby('investSessionId')[['userId']].first().reset_index()
    avgTradeRatio = avgTradeRatio.merge(user_info, on='investSessionId', how='left')

    return avgTradeRatio

avg_trade_ratio(df)

C:\Users\user\AppData\Local\Temp\ipykernel_7440\804191643.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transcation_df['is_buy'] = np.where(
C:\Users\user\AppData\Local\Temp\ipykernel_7440\804191643.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transcation_df['is_sell'] = np.where(

,investSessionId,highBuyRatio,lowBuyRatio,midBuyRatio,highSellRatio,lowSellRatio,midSellRatio,userId
0,b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',0.379310,0.172414,0.448276,0.176471,0.294118,0.529412,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
1,b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
2,b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
3,b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',0.409091,0.227273,0.363636,0.000000,1.000000,0.000000,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
4,b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
5,b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"
6,b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,0.214286,0.571429,0.214286,0.227273,0.659091,0.113636,"b'33""""\x11\x11\x11\xc1UUUUUUDD'"

In [237]:
data = avg_trade_ratio(df)

sell = data[["userId","investSessionId","highSellRatio","midSellRatio","lowSellRatio"]]
buy = data[["userId","investSessionId","highBuyRatio","midBuyRatio","lowBuyRatio"]]

C:\Users\user\AppData\Local\Temp\ipykernel_7440\804191643.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transcation_df['is_buy'] = np.where(
C:\Users\user\AppData\Local\Temp\ipykernel_7440\804191643.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transcation_df['is_sell'] = np.where(

In [238]:
sell

,userId,investSessionId,highSellRatio,midSellRatio,lowSellRatio
0,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',0.176471,0.529412,0.294118
1,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',0.000000,0.000000,0.000000
2,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,0.000000,0.000000,0.000000
3,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',0.000000,0.000000,1.000000
4,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',0.000000,0.000000,0.000000
5,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,0.000000,0.000000,0.000000
6,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,0.227273,0.113636,0.659091

In [239]:
sell["Type"] = "Sell"
sell

C:\Users\user\AppData\Local\Temp\ipykernel_7440\2668896092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sell["Type"] = "Sell"

,userId,investSessionId,highSellRatio,midSellRatio,lowSellRatio,Type
0,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'?@%\x13s\x7f\xff3\xaa=0\xe1\xfd\xb0\x91\xba',0.176471,0.529412,0.294118,Sell
1,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'|L3\xf6{_B%9\xf2\xaa:\x87\x8f\x17\x9b',0.000000,0.000000,0.000000,Sell
2,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xbcD\xb4\x1c\xe1\xe1\x9ce\xb9M\xa4>\x13\x1e...,0.000000,0.000000,0.000000,Sell
3,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xd9H\x15r\xe5\xb3L\xa6S<\x8a\xcde5)\x9c',0.000000,0.000000,1.000000,Sell
4,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xdfM\x87\x01\xe0a\xe9X\x10\xfb\x8d{e\rJ\x96',0.000000,0.000000,0.000000,Sell
5,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xe1B\x96\xaeP\x99\x1b\x0f\xa4@\xdd~\x1a\xd5...,0.000000,0.000000,0.000000,Sell
6,"b'33""""\x11\x11\x11\xc1UUUUUUDD'",b'\xe7M\x8c\x06/\x9a7\x02K\rg\xcd\xa3\xe6\xad\...,0.227273,0.113636,0.659091,Sell

In [240]:
df = data

Sell = ["highSellRatio","midSellRatio","lowSellRatio"]
Buy = ["highBuyRatio","midBuyRatio","lowBuyRatio"]

all_types = [("Sell", Sell), ("Buy", Buy)]

# 우리 아이랑 같은 나이를 갖는 행만 필터링
child_age = df.loc[df["childId"]==userId, "age"].iloc[0] 
df = df[df["age"] == child_age].copy()
for label, col_list in all_types:
    for col in col_list:
        # 우리아이 나이대 평균
        col_mean = df[f"{col}"].mean()
        new_col = col.replace(label, "")
        df[f'{new_col}_age'] = col_mean

KeyError: 'childId'